#!/bin/bash

echo -e "\nSTART AT:" $(date +%d\ %h\ %Y,\ %H:%M:%S) "\n"

echo -e "Cleaning previous stuff"
	rm -fr [0-9]* # clean previous timesteps
	rm -fr processor* log_solve postProcessing VTK
	cp -r orig0 ./0
	mkdir log_solve
echo -e "  --> Done"

# ==================== CORES LOADING ===========================
# load np directly from initialConditions, no need for Processors file
mock="$(grep 'np' initialConditions | awk '{print $2}')"
np=${mock:0:${#mock}-1}
# ================================================================

echo -e "\nDecomposing case for " $np 'processor(s)';
	decomposePar > log_solve/01_decomposePar
echo "  --> Done";

echo -e "\nRenumbering mesh";
	mpirun -np $np renumberMesh -overwrite -latestTime -parallel > log_solve/02_renumberMesh
echo "  --> Done";

echo -e "\nSolving potentialFoam";
	mpirun -np $np potentialFoam -parallel > log_solve/03_potentialFoam
echo -e "  --> Done";

echo -e "\nSolving simpleFoam";
	mpirun -np $np simpleFoam -parallel > log_solve/04_simpleFoam
echo -e "  --> Done";

echo -e "\nPostprocessing:"
# echo "	functionObjects"
#	simpleFoam -postProcess -latestTime -parallel > log_solve/05_functionObjects
echo "	Lambda2"
	mpirun -np $np postProcess -func "Lambda2" -latestTime -parallel > log_solve/06_Lambda2
echo "	totalPressureIncompressible"
	mpirun -np $np postProcess -func "totalPressureIncompressible(p,U,rhoInf=1.225)" -latestTime -parallel > log_solve/07_totalPressureIncompressible
echo "	mag(vorticity)"
	mpirun -np $np postProcess -func "mag(vorticity)" -latestTime -parallel > log_solve/08_magVorticity
echo -e "  --> Done";

echo -e "\nReconstructing case";
	reconstructPar -latestTime > log_solve/10_reconstructPar
echo "  --> Done";

echo -e "\nReconstructing fields";
	reconstructPar -withZero -fields '(phi)' -latestTime > log_solve/11_reconstructPar0
echo "  --> Done";

echo -e "\nZipping processors to free some space";

mkdir allProcessors

mv processor* ./allProcessors

#echo -e "\nfoamToVTK";
#	foamToVTK -latestTime > log_solve/13_foamToVTK
#echo "  --> Done";
touch /home/$USER/OpenFOAM/pietro-v2312/run/ended.txt

echo -e "\nEND AT:" $(date +%d\ %h\ %Y,\ %H:%M:%S)
